CLASS zcx_incomplete_car DEFINITION
  PUBLIC
  CREATE PUBLIC
  INHERITING FROM cx_dynamic_check.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_incomplete_car IMPLEMENTATION.
ENDCLASS.
